config/routes.rb
Connectioncrm::Application.routes.draw do
  resources :departments

  devise_for :users
  root :to => "pages#home"

end

app/models/department.rb
class Department < ActiveRecord::Base
  validates :name, :presence => true, :length => { :maximum => 40 }, :uniqueness => true
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @departments = Department.paginate :page => params[:page], :per_page => 5
  end

  # GET /departments/1
  # GET /departments/1.xml
  def show
    @department = Department.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @department }
    end
  end

  # GET /departments/new
  # GET /departments/new.xml
  def new
    @department = Department.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @department }
    end
  end

  # GET /departments/1/edit
  def edit
    @department = Department.find(params[:id])
  end

  # POST /departments
  # POST /departments.xml
  def create
    @department = Department.new(params[:department])

    respond_to do |format|
      if @department.save
        format.html { redirect_to(@department, :notice => 'Department was successfully created.') }
        format.xml  { render :xml => @department, :status => :created, :location => @department }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @department.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /departments/1
  # PUT /departments/1.xml
  def update
    @department = Department.find(params[:id])

    respond_to do |format|
      if @department.update_attributes(params[:department])
        format.html { redirect_to(@department, :notice => 'Department was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @department.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.xml
  def destroy
    @department = Department.find(params[:id])
    @department.destroy

    respond_to do |format|
      format.html { redirect_to(departments_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :authenticate_user!, :except => :home
  
  def home
  end

  def contact
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/departments/_form.html.erb
  <div class="group">
    <%= f.label :name, t("activerecord.attributes.department.name", :default => "Name"), :class => :label %>
    <%= f.text_field :name, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>
        
<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>
  <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
	<%= link_to t("web-app-theme.cancel", :default => "Cancel"), departments_path, :class => "text_button_padding link_button" %>
</div>

app/views/departments/_sidebar.html.erb
<div class="block notice">
  <h3>Ajuda</h3>
  <div class="content">
    <p>Cadastramento de departamentos. 
	Pode ser um departamento como Qualidade, Diretoria, Engenharia, Suprimentos, Manutencao, Compras, etc.</p>
  </div>
</div>

app/views/departments/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", departments_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_department_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_department_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> <%= Department.model_name.human %></h2>
    <div class="inner">
      <%= form_for @department, :url => department_path(@department), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/departments/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", departments_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_department_path %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %>: <%= Department.model_name.human %></h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">ID</th>
                    <th>
            <%= t("activerecord.attributes.department.name", :default => t("activerecord.labels.name", :default => "Name")) %>
          </th>
                    <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @departments.each do |department| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= department.id %>
          </td>
                    <td>
            <%= link_to department.name, department_path(department) %>
          </td>
                    <td>
            <%= l(department.created_at, :format => :short)  %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", department_path(department) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_department_path(department) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", department_path(department), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>          
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
        <%= will_paginate @departments, :previous_label => 'Anterior', :next_label => 'Próxima'  %>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/departments/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", departments_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_department_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  <%= Department.model_name.human %></h2>
    <div class="inner">
      <%= form_for :department, :url => departments_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/departments/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", departments_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_department_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", department_path %></li>
    </ul>
  </div>          
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.department.name", :default => t("activerecord.labels.name", :default => "Name")) %>:</b>
          <%= @department.name %>
        </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_department_path(@department), :class => "button" %> 
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), department_path(@department), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ConnectionCrm - CRM Web Application</title>
  <%= stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/bec/style", "web-app-theme/override", :cache => true %>
  <%= javascript_include_tag :defaults, :cache => true %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <div id="header">
      <h1><a href="/">ConnectionCrm - CRM Web Application</a></h1>
      <div id="user-navigation">
        <ul class="wat-cf">
	        <% if user_signed_in? -%>
              <li>	          
                <!-- link_to  t("web-app-theme.settings", :default => "Settings"), 
                    root_path -->
              </li>	
	          <li>	          
	            <%= link_to  t("web-app-theme.profile", :default => "My Info") + ' (' + current_user.email  + ') ' , 
	                edit_user_registration_path %>
	          </li>
	          <li>
	            <%= link_to 'Sign out', destroy_user_session_path %>
	          </li>
	        <% else %>
              <li><%= link_to t("web-app-theme.login", :default => "Log in"), new_user_session_path %></li>
	        <% end -%>
        </ul>
      </div>
	  <div id="main-navigation">
	    <ul class="wat-cf"> 
	      <li class="<%= controller.controller_path == 'pages' ? 'active' : '' %>">
		      <a href="<%= root_path %>">Home</a>
		  </li>	
		 <li class="<%= controller.controller_path == 'departments' ? 'active' : '' %>"><a href="<%= departments_path %>">Departments</a></li></ul>
	  </div>
    </div>    
    <div id="wrapper" class="wat-cf">
      <div class="flash">
        <% flash.each do |type, message| -%>
          <div class="message <%= type %>">
            <p><%= message %></p>
          </div>
        <% end -%>
      </div>
      <div id="main">
        <%= yield %>
        <div id="footer">
          <div class="block">
            <p>Copyright &copy; <%= Time.now.year %> ConnectionCrm - CRM Web Application.</p>
          </div>      
        </div>
      </div>
      <div id="sidebar">
        <%= yield :sidebar %>
      </div>
    </div>    
  </div>
</body>
</html>

app/views/layouts/sign.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ConnectionCrm - CRM Web Application</title>
  <%= stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/bec/style", "web-app-theme/override", :cache => true %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
	<div id="wrapper" class="wat-cf">
      <div id="box">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/pages/_sidebar.html.erb
<div class="block">
  <h3>Links</h3>
  <ul class="navigation">
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to Department.model_name.human, departments_path %></li>
    <% if user_signed_in? -%>
      <li>
        <%= link_to 'Sign out', destroy_user_session_path %>
      </li>
    <% else %>
      <li>
        <%= link_to t("web-app-theme.login", :default => "Log in"), new_user_session_path %>
      </li>
    <% end -%>
  </ul>
</div>

<div class="block notice">
  <h3>Ajuda</h3>
  <div class="content">
    <p>Esta aplicacao tem atualmente suas funcionalidades em desenvovimento e passando por fases de teste.</p>
  </div>
</div>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<div class="block" id="block-text">  
  <div class="content">
    <h2 class="title">ConnectionCrm - CRM Web Application</h2>
    <div class="inner">
      <p class="first">
	    Esta é uma aplicação web oferecida na forma de 'Software como Servico'
	    <a href="http://pt.wikipedia.org/wiki/Software_como_servi%C3%A7o">Saas (Software as a Service)</a>
      </p>
      <hr />
	  <h3>Principais funcionalidades</h3>
  	  <ul class="list">
	
	    <li><span>Cadastramento de Contatos</span></li>
	    <li><span>Opcoes para cadastramento de caracteristicas dos contatos</span></li>
	    <li><span>Pesquisa por informacoes registradas no cadastro de contatos</span></li>
	    <li><span>Agrupamento de contatos por grupos</span></li>
        <li><span>outras em desenvolvimento...</span></li>
	  </ul>
      <p> 
	    <span class="gray">
	      <span class="hightlight">Garantia de backup:</span> 
	      ConnectionCrm - CRM Web Application, faz backup automatico de 
	      todas as informacoes registradas.
	    </span>
	  </p>
      <hr />
      <p>
        Cadastre seus contatos e visualize-os de forma simples, apresentados na tela. 
        Em apenas uma tela você será capaz de ver seus contatos de negocios, clientes ou outros grupos que
        voce defirnir.
        <span class="hightlight">Os grupos definidos sao dinamicos e voce pode muda-los a qualquer momento.</span>
      </p>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>